# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
DISABLE_AUTO_UPDATE="true"
plugins=(git bundler)

source $ZSH/oh-my-zsh.sh
#source ~/.oh-my-zsh/plugins/git/git.plugin.zsh

# User configuration

# Pure prompt

autoload -U promptinit; promptinit

PURE_CMD_MAX_EXEC_TIME=0
PURE_GIT_PULL=0
PURE_PROMPT_SYMBOL=➜

# zstyle :prompt:pure:path color green

#prompt pure

source /usr/share/zsh/scripts/git-prompt.zsh
#export PROMPT="%~%F{#66b2b2}$(current_branch_prompt)%f > "
source $HOME/.gitprompt.zsh

export EDITOR="vim"
export CODE_DIR=$HOME/code

# rbenv
# export PATH="$HOME/.rbenv/bin:$HOME/pkgs/tfenv/bin:$PATH"
eval "$(rbenv init -)"

# eval `dircolors ~/.dir_colors`

# set vi mode for zsh
bindkey -v

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[[ $DISPLAY ]] && source ~/.scripts/keyboard_off.sh

alias zxcvb="sudo loadkeys us"
alias z="setxkbmap us"
alias x="setxkbmap us -variant colemak;xmodmap ~/.xmodmaprc"

alias rinse="mplayer -playlist http://r3.dgen.net:8000/rinseradio.m3u -cache 100"
alias webcam='mpv av://v4l2:/dev/video0' # press s to take picture
alias screen-capture='ffmpeg -f x11grab -y -r 30 -s 1920x1080 -i :0.0 -vcodec huffyuv out.avi' # very high quality
alias editgit='vim ~/.oh-my-zsh/plugins/git/git.plugin.zsh;source ~/.zshrc'
alias n="cd $HOME/notes"
fbn() { find . -iname \*$*\* }

alias -s jpg=feh
alias -s mkv=mpv
alias -s mp4=mpv
alias -s rb=vim
alias -s pdf=mupdf

alias bt="bluetoothctl -- power on;bluetoothctl -- connect B8:D5:0B:CF:4C:17"

export ERL_AFLAGS="-kernel shell_history enabled"

test-internet() { while true; do ping -c 1 1.1.1.1; sleep 1; done }

alias screenshot-output="convert label:@- output-screenshot.png"
alias ten-biggest-dirs="du -hs */ | sort -hr | head"

if [ -f ~/.zshrc-local ]; then
  source ~/.zshrc-local
fi

alias editlocal="vim ~/.zshrc-local;source ~/.zshrc-local"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export FLYCTL_INSTALL="/home/muunbeam/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

alias rebuild_ruby_ctags="git ls-files | ctags --links=no --languages=ruby -f .tags -L-"
# g] can be used to replace the current tab and search all tags
# C-] can be used to open the definition
# try starscope gem
# want to be able to open new tab...idk how with vim

alias light="
  kitten themes --reload-in=all --cache-age -1 Kaolin Breeze
  echo 'set background=light' > ~/.vimrc.color
  feh --no-fehbg --bg-scale '/home/muunbeam/.main_1500.jpg'"
alias dark="
  kitten themes --reload-in=all --cache-age -1 Sakura Night
  echo 'set background=dark' > ~/.vimrc.color
  feh --no-fehbg --bg-scale '/home/muunbeam/.main_1500_dark.jpg'"

setopt SHARE_HISTORY
export HISTFILE=$HOME/.zhistory
export SAVEHIST=100000
export HISTSIZE=9999
setopt HIST_EXPIRE_DUPS_FIRST

bindkey ^R history-incremental-search-backward

alias restart-bluetooth="systemctl --user restart pipewire"
alias restart-time="sudo systemctl start ntpd;sudo timedatectl set-ntp true;sudo timedatectl set-ntp false;"

alias rubo="rubocop -A"
